### ISSUE TITLE
Unclear README

### ISSUE THREAD

**Issue by tomekowal** [jfreeze/horizon#3]
Hi! Thanks for the project. I saw it linked on BlueSky and wanted to check what it does.

```
Installs Elixir, Erlang, Postgres and Postgres databases
```

Why Postgres is there twice? Are "Postgres" and "Postgres databases" different things?

**Comment by jfreeze** [comment]
Yes.

You can install Postgres, but that will not create `/var/db/dataXX` where databases are stored.

Once Postgres is installed, you can install/create multiple databases.

**Comment by tomekowal** [comment]
Ah! Thanks for explaining. I'd change it to "Installs Postgres and creates databases" for clarity.
Anyway, I get it now, so I'll close the issue.
